#Uncomment if you don't want to add the hosts to your .ssh/config
#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q guardian.ffmuc.net"'
base_packages:
    - htop
    - tcpdump
    - iftop
    - wget
    - screen
    - ethtool
    - vim
    - mlocate
    - curl
    - sysstat
    - ifupdown2
ntp_manage_config: true
ntp_servers:
  - lab-ntp01.local iburst
  - lab-ntp02.local iburst
users:
    - username: awickert
    - username: krombel
    - username: lukesix
    - username: pkoerner
    - username: virtual
    - username: max
    - username: lakesider
salt_config:
    - master: saltmaster.in.ffmuc.net
    - retry_dns: 30
