---
interfaces_ether_interfaces:
  - device: eth0
    bootproto: static
    address: 195.30.94.25
    netmask: 255.255.255.248
    gateway: 195.30.94.30
    dnsnameservers: 8.8.8.8 8.8.4.4
    dnssearch: ffmuc.net
    ip6:
       address: 2001:608:A01::25
       prefix: 64
       gateway: 2001:608:A01::31
  - device: eth1
    bootproto: static
    address: 192.168.0.50/24
    netmask: 255.255.255.0
    ip6:
       address: 2001:608:a01:ff02::1
       prefix: 64
  - device: eth1:0
    bootproto: static
    address: 10.23.42.1
    netmask: 255.255.255.0
  - device: eth1:2
    bootproto: static
    address: 192.168.1.50
    netmask: 255.255.255.0
  - device: eth1.1000
    bootproto: static
    address: 10.80.248.2
    netmask: 255.255.255.224
  - device: eth1.3000
    bootproto: static
    address: 172.30.0.2
    netmask: 255.255.255.0
  - device: eth1.1200
    bootproto: static
    address: 10.80.240.1
    netmask: 255.255.255.224
extra_packages:
  - pv
  - ansible
  - git
  - isc-dhcp-server
  - radvd
  - atftpd
  - syslinux-utils
  - syslinux
  - virt-manager
  - pdns-recursor

dhcp_global_authoritative: 'authoritative'
dhcp_global_domain_name: 'in.ffmuc.net'
dhcp_subnets:
  - ip: 10.80.248.0
    netmask: 255.255.255.224
    filename: 'pxelinux.0'
    next_server: 10.80.248.2
    domain_name_servers:
      - 10.80.248.6
    routers: 10.80.248.1
    pools:
      - default_lease_time: 1800
        max_lease_time: 3600
        range_begin: 10.80.248.25
        range_end: 10.80.248.30
  - ip: 10.80.240.0
    netmask: 255.255.255.224
    filename: 'pxelinux.0'
    next_server: 10.80.240.1
    domain_name_servers:
      - 1.1.1.1
      - 8.8.8.8
    routers: 10.80.240.1
    pools:
      - default_lease_time: 1800
        max_lease_time: 3600
        range_begin: 10.80.240.10
        range_end: 10.80.240.30
radvd:
    interface:
         - eth1.1200
         - eth1.1000
openvpn_enabled: yes
openvpn_unified_client_profiles: yes
openvpn_key_country: DE
openvpn_key_province: BY
openvpn_key_city: Munich
openvpn_key_org: ffmuc.net
openvpn_key_email: muenchen@freifunk.net
openvpn_key_size: 2048
openvpn_tls_auth: true
openvpn_log: /var/log/openvpn.log
openvpn_host: guardian.ffmuc.net
openvpn_dev: tun
openvpn_server: 10.8.0.0 255.255.255.0
openvpn_push_routes_to_client:
      - route 10.80.248.0 255.255.255.224
      - route 10.80.240.0 255.255.255.224
      - route 172.30.0.0 255.255.255.0
      - dhcp-option DNS 10.80.248.6
